
project_id = "oadpeurpnteaifooowdr"

[global.env]
OPENAI_API_KEY = "{{env.OPENAI_API_KEY}}"
ASSEMBLY_AI_API_KEY = "{{env.ASSEMBLY_AI_API_KEY}}"
SUPABASE_URL = "{{env.SUPABASE_URL}}"
SUPABASE_ANON_KEY = "{{env.SUPABASE_ANON_KEY}}"
