// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oadpeurpnteaifooowdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hZHBldXJwbnRlYWlmb29vd2RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNTU3MDksImV4cCI6MjA1NjczMTcwOX0.2RQv3ubXIMogrni4zt0nYWct4D0ZCf1N-xjhhz4lh28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);